### ISSUE TITLE
Django 2

### ISSUE THREAD

**Issue by juanpabloacierno** [zostera/django-bootstrap4#101]
Got the 'bootstrap4' is not a registered tag library. error on Django 2.0.5 after trying to load a template.
Only added 'bootstrap4' in the config as per documentation. Is there anything I'm missing?

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). Please try to get your answer there.
