### ISSUE TITLE
render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by pozar87** [zostera/django-bootstrap4#109]
Since Django 2.1 the **renderer** argument must be passed explicitly. 

- OS: Manjaro 
- django-bootstrap4: 0.0.6
- python: 3.7
- django: 2.1

Issue should be easy replicated just by upgrade to Django 2.1

**Comment by dyve** [comment]
Can you add a log, an example, or even better: a test that shows this error?

**Comment by pozar87** [comment]
Sure thing, the log is here: [error.log](https://github.com/zostera/django-bootstrap4/files/2309518/error.log), its baiscally failing on rendering [location field](https://github.com/caioariede/django-location-field) with **bootstrap4** styling. I thing I can also provide some minimal test example by tomorrow.

**Comment by dyve** [comment]
A test would be awesome, will wait for that.

**Comment by pozar87** [comment]
Hi!
I've confirmed yesterday the problem lays in **django-location-field** (missing explicit _renderer_ in _LocationWidget.render()_). I was misled by python stack trace, **django-bootstrap4** seems perfectly fine. 
Thanks for quick answer and encouragement for more digging :)
Best Regards!
