### ISSUE TITLE
Putting a link in bootstrap_alert

### ISSUE THREAD

**Issue by doganmeh** [zostera/django-bootstrap4#113]
How do I put a link in `bootstrap_alert`?

```
msg=mark_safe('Please visit our forum site <a href="talk.edgle.com" class="alert-link">Edgle Talk</a> as well!')

render_alert(msg)
'<div class="alert alert-info alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>Please visit our forum site &lt;a href=&quot;talk.edgle.com&quot; class=&quot;alert-link&quot;&gt;Edgle Talk&lt;/a&gt; as well!</div>'
```

As seen, html elements are escaped due to the following chain of commands: 

bootstrap_alert -> render_alert -> render_tag ->format_html -> conditional_escape

**Comment by doganmeh** [comment]
The problem is here `render_alert` line: 26:

`content=button_placeholder + text_value(content),`

str + SafeText => str

**Comment by doganmeh** [comment]
And it would be solved if '__BUTTON__' was marked safe (line 22).

**Comment by dyve** [comment]
Thanks for your patience on this.
