### ISSUE TITLE
Feature request: Allow to skip label from field completely

### ISSUE THREAD

**Issue by xi** [zostera/django-bootstrap4#115]
```
{% bootstrap_field field show_label=False %}
```

currently still renders the label, but with `class="sr-only"`. This is great for most cases, but it is actually a bad idea if the users manually adds the label separately. In that case, both labels will be associated with the form field and the computed aria-label will be "{label} {label}".

**Comment by jieter** [comment]
I agree on this. Can you propose an API for this using a pull request?

**Comment by xi** [comment]
A straigtforward API would be `show_label=True|False|'sr-only'`, but that would be a breaking change.

Maybe `show_label='default'|'sr-only'|'hidden'` where `True` maps to `'default'` and `False` maps to `'sr-only'`  for backwards compatibility.

**Comment by jieter** [comment]
Not sure about 'hidden' since it implies the current `False` to me...

**Comment by dyve** [comment]
What about True|False|None

True = show
False = hide with sr-only
None = nothing at all

**Comment by xi** [comment]
I think False/None are not very descriptive. That's why I would prefer to go with strings.

**Comment by dyve** [comment]
Or as specific extra option aria_support=True|False?

`class="sr-only"` is not an aria-attribute, but it does fall under aria support I'd say.

**Comment by xi** [comment]
I also thought about it and concluded that it is more confusing than helpful.

Can you explain what is wrong with the current approach (note that I changed 'hidden' to 'skip' in the pull request) and why you think the other ideas are better? That could help me to understand the direction you want to go.

**Comment by dyve** [comment]
Thanks all, good discussion.

After re-reading, I come to this first question.

 Do we want to keep True = show label and False = hide label but generate it with sr-only?*

If we were to do a breaking change and allow False = no label at all, we could introduce a new setting "sr-only" which would be quite obvious. What we would lose is the automatic generation of labels for screen readers that we now have, and somehow it feels as if we're doing people that use screen readers a disservice.

Let's tackle this question first.

**Comment by xi** [comment]
@dyve can you please checkout #117? The approach I took there is this:

- Introduce new values 'sr-only' and 'skip' to be explicit
- Map `False` to 'sr-only' for backwards compatibility.
