### ISSUE TITLE
How to compile bootstrap locally / reference local boostrap files

### ISSUE THREAD

**Issue by bwilliams18** [zostera/django-bootstrap4#118]
I'd like to be able to customize bootstrap variables (colors, etc). It seems like the right way to do this is to compile bootstrap locally for the project. I can't figure out how to do this with the django-bootstrap4  app. Or more specifically how to load bootstrap from static files.

**Comment by MeNsaaH** [comment]
Going through the codebase, I think you can override the `BOOTSTRAP_DEFAULTS` from your settings file. `BOOTSTRAP4_DEFAULTS = {
    "css_url": {
        "href": "/static/css/bootstrap.css",
    },`

**Comment by dyve** [comment]
Use the settings as described in https://django-bootstrap4.readthedocs.io/en/latest/settings.html.
