### ISSUE TITLE
uncaught error in fn

### ISSUE THREAD

**Issue by poco1980** [zostera/django-bootstrap4#120]
util.js:56 Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:56
    at util.js:10
    at bootstrap.min.js:6
    at bootstrap.min.js:6
(anonymous) @ util.js:56
(anonymous) @ util.js:10
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6

[error.zip](https://github.com/zostera/django-bootstrap4/files/2462324/error.zip)

I added the settings.py and my base.html to show you i got everything set right i just want to know where the problem is if its on your end or on bootstrap

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
