### ISSUE TITLE
IE compatibility 

### ISSUE THREAD

**Issue by fmatray** [zostera/django-bootstrap4#121]
Hello,
I had an issue issuing IE, the compatibilty switched to IE7...
To bypass this problem I had to add the following line BEFORE any \<link\>, CSS or JS. 
`<meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1" />`

But, it's impossible with the current release without a specific version of bootstrap4.html. 

It would be nice to have a block like {%block bootstrap4_meta %}{% endblock %} in order to add extra \<meta\> options.

Thanks.
Frédéric

**Comment by dyve** [comment]
IE should be in the past for most users now. Please roll your own version of the base template.
