### ISSUE TITLE
Is there an option to mark a form as not required? If no: Add one

### ISSUE THREAD

**Issue by SvenMoenig** [zostera/django-bootstrap4#129]
I have an html form that consists of multiple model forms. Not all of the forms need to be filled out by the user. Thus i would like to make it so that the forms that are not required only cause errors to be displayed if they are filled out partially in an invalid way.

To give a more concrete example:
I have a form for creating a new customer object in the database. This object represents a company. It may have a contact person associated with it. 

For the data of the customer object itself i use a django ModelForm like this:
```python
class NewCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = [
            'customer_id',
            'name',
            'discount_special',
            'provision',
            'reseller',
            'tax_id_number',
            ]
```

notice that there are no fields for the contact person there, because for that i have another ModelForm:

```python
class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'phone',
            ]
```

I do not need information about the contact person to create a customer object, but in the template i use to render these I treat them as one big html-```<form>```-tag so all the information gets submitted with at the same time. It works fine if every field is filled out with valid data. If the fields of the contact person are fully empty, I would like to just create the customer object. For that i need the client-side validation to allow submitting the whole html-form even though the part for the contact person is empty. Currently it seems like i need to write some custom JS to achieve that.

I would really like if there was a parameter like this to specify that the form as a whole may be empty (or invalid):
```DTL
{% bootstrap_form contact required=False %}
```

Is there a parameter that works like this?

P.S.: This issue aside i think that django-bootstrap4 works pretty well for me, so GOOD JOB!

EDIT: Make the wording more precise

**Comment by ikcam** [comment]
You are looking for `Formsets` and have nothing to do with this particular module. You can also try

```python
class ContactForm(ModelForm):
    name = forms.CharField(required=False)
    email = ...
    phone = ...

    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'phone',
            ]
```

https://docs.djangoproject.com/es/2.1/topics/forms/formsets/

**Comment by SvenMoenig** [comment]
Correct me if I'm wrong, but aren't `Formsets` only for multiple forms of the same type? @ikcam

**Comment by ikcam** [comment]
You aren't wrong but as you can see on the Django Admin you are able to attach a Form a Formset on a single view inside the same HTML. `<form>` tag

**Comment by SvenMoenig** [comment]
> you are able to attach a Form a Formset on a single view inside the same HTML `<form>` tag.

which is what i did. sorry if i was not precise enough with my description of my use-case.

**Comment by ikcam** [comment]
Them probably the issue is inside your Formset definition

```python
ContactFormset = inlineformset_factory(
    Customer,
    Contact,
    form=ContactForm,
    min_num=0,
)
````

Probably the `min_num` attribute isn't right, if is equal/greater than 1 it will ask you to fill at least 1 form. Or is there another error?

**Comment by SvenMoenig** [comment]
oh wait i think i misread your previous answer, my bad.
I did render both the mentioned Forms in the same html-tag, but i did not put the not required one in a Formset. I'm gonna try that. Thanks for the idea.
