### ISSUE TITLE
Documentation project on readthedocs is taken

### ISSUE THREAD

**Issue by dyve** [zostera/django-bootstrap4#13]
See if we can work something out with @bitkits.

See https://github.com/bitkits/bootstrap4-django/issues/1

**Comment by jieter** [comment]
Seems to be fixed: http://django-bootstrap4.readthedocs.io/en/latest/

**Comment by dyve** [comment]
https://github.com/rtfd/readthedocs.org/issues/3195

**Comment by dyve** [comment]
Fixed by readthedocs
