### ISSUE TITLE
XSS in placeholder values

### ISSUE THREAD

**Issue by rixx** [zostera/django-bootstrap4#134]
Placeholder values are run through `mark_safe` when building form widgets. That's not a good idea, as it permits XSS content. As placeholders are often generated automatically from labels, and labels are properly escaped, this is unexpected behaviour.

This behaviour was introduced in 5b98fd5e5a750bb8588eb92569db324b736c736e. The commit doesn't give a reason for the introduction (and neither does the PR at https://github.com/dyve/django-bootstrap3/pull/385).

I've included a fix in #135, including tests so you can see the behaviour for yourself.

**Comment by dyve** [comment]
Agreed. Thx for the PR. Will look at it ASAP. If you have a chance to look at the flake8 fail, that would be super.

**Comment by rixx** [comment]
Done, was just the line-length in the test. Fix is pushed.
