### ISSUE TITLE
Potential issue with the autogenerated button to models.ImageField input in forms

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [zostera/django-bootstrap4#138]
Hello
I dont know whether it an  issue or not but how to change language of the  automatically generated button in {%   bootstrap_form form layout='inline'%} (generated to ImageField.Model input area)? Please refer to the image bellow:
![1](https://user-images.githubusercontent.com/47420076/54940130-2a214900-4f3b-11e9-965e-095882e62bd9.jpg)
I would like to change it from Russian to English.

settings.py languages data:

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

template full code:

{% extends "base.html" %}
{% load bootstrap4 %}
{%  bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %} Adding new boat{% endblock title %}
{% block content %}
<div class="container-fluid">

<form method="post">
    {%  csrf_token %}
    {%   bootstrap_form form layout='inline'%}  <-- button generated here!!!
    <button type="submit" class="btn btn-light">Submit data</button> < -- my own button

</form>

</div>
{% endblock content %}

Thank you in advance and sory if quetstion is stupid...

**Comment by dyve** [comment]
The button will be in browser language I think, not in your Django language.
