### ISSUE TITLE
"exclude" not working.

### ISSUE THREAD

**Issue by PSNick** [zostera/django-bootstrap4#148]
I'm attempting to exclude a single option from a form field, but it doesn't appear to be doing anything:

relevant html
```html
<form id="form_id_parsley">
    {% bootstrap_field form.seed show_label=False %}
    {% bootstrap_field form.tile_size exclude="140" show_label=False %}
    <button type="submit" class="btn btn-primary" id="generate">Generate</button>
</form>
```

forms.py
```python
TILE_SIZE = [
    (28, "Mockup: 28px"),
    (70, "Standard: 70px"),
    (140, "High-Res: 140px")
]

class DungenForm(forms.Form):
    seed = forms.RegexField(r'^[0-9a-zA-Z]*$', required=False, max_length=12,
                            help_text="Leave blank for a random dungeon.", strip=True)
    tile_size = forms.ChoiceField(required=False, choices=TILE_SIZE, initial=70,
                                  help_text="Tile size - generation will be faster will smaller tile sizes.")
```

Am I'm doing something wrong or is it perhaps a bug?

**Comment by dyve** [comment]
The "exclude" parameter is not for excluding select options. It is for excluding fields from a complete form.

**Comment by PSNick** [comment]
Thank you for the clarification @dyve ! I saw it under bootstrap_form and bootstrap_field in the documentation so I was under the impression it should work this way as well.
Is there any way to achieve what I was trying to do?
