### ISSUE TITLE
input group add-on between two inputs

### ISSUE THREAD

**Issue by will-emmerson** [zostera/django-bootstrap4#152]
Is there a way of having an input group add-on between two inputs without resorting to raw html?
Like this:
![Screenshot from 2019-06-18 12-05-31](https://user-images.githubusercontent.com/2007875/59677385-98d01480-91c1-11e9-9aea-718f05a8f3ad.png)

The raw html looks something like this, where `form.start_time` has been given the class `form-control`:

```html
<div class="input-group">
    {{ form.start_time }}
    <div class="input-group-prepend input-group-append">
        <span class="input-group-text">to</span>
    </div>
    {{ form.end_time }}
</div>
```

Unfortunately this doesn't show errors though.

I tried something like the following which does include errors but it didn't really work because of all the extra divs around the inputs:

```html
<div class="input-group">
    {% bootstrap_field form.start_time show_label=false form_group_class='' field_class='' %}
    <div class="input-group-prepend input-group-append">
        <span class="input-group-text">to</span>
    </div>
    {% bootstrap_field form.start_time show_label=false form_group_class='' field_class='' %}
</div>
```

**Comment by dyve** [comment]
This is not something you can do out of the box. You are trying to mix 2 inputs. The best place to ask for help is [StackOverflow](https://stackoverflow.com). 

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
