### ISSUE TITLE
Make six a dependency

### ISSUE THREAD

**Issue by rixx** [zostera/django-bootstrap4#153]
Django 3.0 will drop `django.utils.six`, so the choices are to either remove six (and hence Python 2 support) or to use `six` directly.

**Comment by frost-nzcr4** [comment]
Django drops support of the old python version, as well as Python community drops 2.7 support after 2020, so six isn't need anymore.

**Comment by dyve** [comment]
We'll drop support for Python 2 and Django 1 altogether soon.

**Comment by rixx** [comment]
Do you have an estimate of what "soon" is?

**Comment by dyve** [comment]
There is a PR on django-bootstrap3 to drop Python 2 and Django 1. When that is done, we'll do the same procedure on django-bootstrap4. I'd say within a few weeks.

**Comment by dyve** [comment]
We'll drop it in #155
