### ISSUE TITLE
bootstrap4_title is missing unintentionally, or removed intentionally but missing from MIGRATE.rst

### ISSUE THREAD

**Issue by ippeiukai** [zostera/django-bootstrap4#156]
We are migrating from `django-bootstrap3`. `bootstrap4_title` is expected to be there as `bootstrap3_title` equivalent, but missing since 0.0.2.

https://github.com/zostera/django-bootstrap4/commit/a1e3e224ddf3ee9c0ebe1636b1c6e77dc9ef083e#diff-633f4829fde452dc2057d9ba1f930af2L9

If the change is intentional, it should be in `MIGRATE.rst`.

**Comment by dyve** [comment]
Thanks, this was a mistake. I am adding it back and adding a test.
