### ISSUE TITLE
Documentation out-of-date

### ISSUE THREAD

**Issue by se-bastiaan** [zostera/django-bootstrap4#172]
The current documentation seems to be out-of-date.

In 1.0.0 `dismissable` was renamed to `dismissible` (#142) which is not yet reflected [here](https://django-bootstrap4.readthedocs.io/en/latest/templatetags.html#bootstrap4.templatetags.bootstrap4.bootstrap_alert).

**Comment by jieter** [comment]
You are right, docs builds are still tried with py27, for which django==2.2 is not an installable version. I'll make sure to fix that soon.

**Comment by jieter** [comment]
Juist fixed the build, up-to-date docs available here: https://django-bootstrap.readthedocs.io/en/latest/
