### ISSUE TITLE
Link to demo project is broken in your documentation

### ISSUE THREAD

**Issue by matthpau** [zostera/django-bootstrap4#182]
In your documentation
https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html#demo-application
You have a link to the demo app:
https://github.com/zostera/django-bootstrap4/tree/master/demo
This is broken and does not work.

**Comment by dyve** [comment]
Thanks, fixed in upcoming release.

**Comment by dyve** [comment]
Fixed in v1.1.0
