### ISSUE TITLE
Unable to make this work with JQuery 3.4.1 even after changing default Bootstrap4 values

### ISSUE THREAD

**Issue by pwalimbe** [zostera/django-bootstrap4#184]
Have updated jquery_url and other parameters to include jquery 3.4.1 -- but it is not working and does not load the new libraries. I calculated and provided integrity values also. Only the default values are working.

**Comment by dyve** [comment]
Can you share some example code?

**Comment by dyve** [comment]
I added a test, and I cannot reproduce the issue. I will merge the test into an upcoming release. If the problem persists for you, please share the relevant parts of your settings and template files.
