### ISSUE TITLE
Currently Fails with Django 3

### ISSUE THREAD

**Issue by glassresistor** [zostera/django-bootstrap4#193]
Here is the error
Django dropped python 2 support and therefore six

```
    from __future__ import unicode_literals
    
    from math import floor
    
    from django import template
    from django.contrib.messages import constants as message_constants
    from django.template import Context
>   from django.utils import six
E   ImportError: cannot import name 'six' from 'django.utils' (/home/mikela/miniconda3/envs/data_warehouse/lib/python3.7/site-packages/django/utils/__init__.py)

../../miniconda3/envs/data_warehouse/lib/python3.7/site-packages/bootstrap4/templatetags/bootstrap4.py:9: ImportError
```

**Comment by dyve** [comment]
This has already been fixed. Which version are you using?

**Comment by NakonechnyiMykhail** [comment]
django==3.0
python==3.8
win10
I have added 'bootstrap4' at INSTALLED_APPS and haven't used any content yet.

`Exception in thread django-main-thread:
...
...
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bootstrap4'
...
....
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
`

**Comment by ikcam** [comment]
But, have you installed it? Looks like you haven't installed it yet.

`pip install -U django-bootstrap4`

**Comment by NakonechnyiMykhail** [comment]
hm, my fail. 
in pycharm after re-installing, it has been fine

**Comment by dyve** [comment]
Thanks for reporting, glad you found the solution.
