### ISSUE TITLE
bootstrap_pagination tag does not use Bootstrap 4 classes

### ISSUE THREAD

**Issue by AndrewKlopper** [zostera/django-bootstrap4#20]
The bootstrap_pagination tag does not not include the "page-item" class on "li" tags or the "page-link" class on "a" tags as required by Bootstrap 4. As a result, pagination links are unstyled.

**Comment by jieter** [comment]
@AndrewKlopper confirmed.

Are you able and willing to contribute a patch? Please open a pull request!

**Comment by jieter** [comment]
Ah, spoke to quick, there already is one

**Comment by jieter** [comment]
#19 is merged, adds this.
