### ISSUE TITLE
Load jQuery before Bootstrap

### ISSUE THREAD

**Issue by christianwgd** [zostera/django-bootstrap4#200]
Hi, when I use the bootstrap4/bootstrap4.html base template I don't find the right place to load the jQuery library. All options I tried result in jquery loading after bootstrap which leads to an error TypeError: undefined is not an object (evaluating 'i.fn') (https://stackoverflow.com/questions/9227406/bootstrap-typeerror-undefined-is-not-a-function-has-no-method-tab-when-us).
Using the tag  {% bootstrap_javascript jquery='full' %} is not compatible with the bootstrap4 base template, although it looks good on the first view but leads to loading bootstrap library twice which gives an error that for example dropdowns open not on the first click (described here https://stackoverflow.com/questions/24218663/avoid-having-to-double-click-to-toggle-bootstrap-dropdown ). 
Could someone please clarify the intended use of the bootstrap4 base template and where to load jquery? At this time i copied the bootstrap4 base template to my project and added the jquery option to the template tag.
Thanks a lot, Christian

**Comment by dyve** [comment]
See the example app, which uses the template and loads all necessary JavaScript.

**Comment by christianwgd** [comment]
I really thought, I had, but after using django-bootstrap for years I found the setting "include_jquery": True,". Sorry for bothering and thanks for the right hint...

**Comment by dyve** [comment]
No problem Christian, glad to help! Take care!
