### ISSUE TITLE
No module named '_version'

### ISSUE THREAD

**Issue by pinduvm** [zostera/django-bootstrap4#201]
Hi, first sorry for my english. I'm from argentina.
I have the next error.

> **ModuleNotFoundError: No module named '_version'**

i'm using

> Django 3.0
> python 3.8
> django-bootstrap4

thanks for we help

**Comment by nim65s** [comment]
Hi,

Same issue for me.
I think https://github.com/zostera/django-bootstrap4/pull/191 fix this, but I'll wait for a release.

Meanwhile, `pip install django-bootstrap4!=1.1.1` works :)

**Comment by dyve** [comment]
Thanks, will make a new release soon.

**Comment by pinduvm** [comment]
very thanks!!!! now work with django-bootstrap4!=1.1.1. Best regards
