### ISSUE TITLE
Documentation: Link to demo project is still broken

### ISSUE THREAD

**Issue by HappyMiner** [zostera/django-bootstrap4#204]
Hello,

Today I found that the link at [https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html](https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html) in section [https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html#demo-application](https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html#demo-application) is returning a 404 from GitHub (offending [link](https://github.com/zostera/django-bootstrap4/tree/master/demo)).

This was previously reported in https://github.com/zostera/django-bootstrap4/issues/182 but was apparently not fixed or resurfaced.

**Update**: Adding screenshot for documentation showing error message after following the link.
![git404](https://user-images.githubusercontent.com/11057169/79405390-db6fa280-7fc6-11ea-8f34-c131bf790fab.jpg)

**Comment by dyve** [comment]
Has since been fixed, apologies.
