### ISSUE TITLE
Documentation: Cloning and running the example fails

### ISSUE THREAD

**Issue by HappyMiner** [zostera/django-bootstrap4#205]
Hello,

I tried to get the example mentioned in https://github.com/zostera/django-bootstrap4/tree/master/example to run, but it completely fails. 

From the documentation in [README.rst](https://github.com/zostera/django-bootstrap4/blob/master/example/README.rst) it is not clear if the git command and the consecutive cd ... command should be run as one or not. In any case after cloning the repository one needs to run "cd django-bootstrap4/example" manually from the right place, otherwise it fails. "pip install -r requirements.txt python manage.py migrate python manage.py runserver" Does not install the required Django dependency, not sure what it is good for?

I tried to do a manual "pip install django" but then I get: "ModuleNotFoundError: No module named 'bootstrap4'" after trying to run the server.

Running a separate pip install django-bootstrap4 in the example folder solved this, but somehow this does not feel right...

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
