### ISSUE TITLE
Support for New Bootstrap Icons (official Bootstrap icon library) v1.0.0-alpha3

### ISSUE THREAD

**Issue by f0rest8** [zostera/django-bootstrap4#207]
Will there be support for [Bootstrap Icons](https://icons.getbootstrap.com/#install), Bootstrap's first-ever icon library?

**Comment by guettli** [comment]
I am not the maintainer of this repo, but from module-architecture perspective I think the bootstrap icons should be a separate project.

**Comment by guettli** [comment]
Here are some docs about icons: https://django-bootstrap4.readthedocs.io/en/latest/migrate.html#icons

**Comment by dyve** [comment]
Yes (thanks @guettli), this would be for https://github.com/zostera/django-icons.
