### ISSUE TITLE
Parameter "form" should contain a valid Django Form.

### ISSUE THREAD

**Issue by ashish2020kashyap** [zostera/django-bootstrap4#208]
![error](https://user-images.githubusercontent.com/63086439/79779001-3ef72880-8357-11ea-91cf-b52a99a21d61.png)

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!

**Comment by ashish2020kashyap** [comment]
Fine
