### ISSUE TITLE
Start with "Why?"

### ISSUE THREAD

**Issue by guettli** [zostera/django-bootstrap4#209]
Hi,

thank you for the docs.

Just one tiny note: Please start with "why?" or the cool benefits and reasons why this project exists **before** starting with "how to install".

Here is my point of view elaborated: https://github.com/guettli/programming-guidelines/blob/master/README.md#love-your-docs

**Comment by bnabled** [comment]
I actually came accross this documentation and have exactly That question. Not sure why I should use this instead of just using the full bootstrap with all the options it brings and build a transferable skill outside of Django.

Want to be confidenced though...

**Comment by tomj** [comment]
@guettli I tend to concur - would you be interested in working on a PR together to address this?

**Comment by guettli** [comment]
@tomj I don't know why this project exists and which benefits it brings.

**Comment by tomj** [comment]
@guettli apologies I'm confused - didn't you open this issue?

**Comment by guettli** [comment]
@tomj yes, I opened the issue.
