### ISSUE TITLE
Incorrect presentation of ImageField and Label

### ISSUE THREAD

**Issue by ArnavVarshney** [zostera/django-bootstrap4#212]
The library doesn't render ImageFields correctly. There is no newline after the label of the field. Please fix that.

[Sample Image](https://i.imgur.com/x2SzXSK.jpg)

**Comment by JulianPedro** [comment]
I'm having the same problem!

**Comment by dyve** [comment]
That part is generated by Django. I agree the rendering does not look very nice. Let's see what we can do.

**Comment by ArnavVarshney** [comment]
> That part is generated by Django. I agree the rendering does not look very nice. Let's see what we can do.

Hmm okay. Just a new line after the label would have been great.

**Comment by dyve** [comment]
@ArnavVarshney If you can submit a code snippet or a PR that would speed things up.

**Comment by ArnavVarshney** [comment]
@dyve I wouldn't mind doing that, to be honest, I don't really know how I can test the changes I make locally. Can I manually compile this repo and use it in my project?

**Comment by dyve** [comment]
Yes, you can clone it and edit it locally. You can also download it and copy it into your project and tinker with it. This might get you started: https://opensource.com/article/19/7/create-pull-request-github

For more in-depth questions, I'm going to refer you to StackOverflow.

Happy coding!

**Comment by ArnavVarshney** [comment]
@dyve I did manage to fix it but I am not sure if the pull request was as desired though. This is my first time contributing to a public project!

**Comment by JulianPedro** [comment]
I solved the problem by adding label_class = 'row', I don't know if it's the best idea but it works.

**Comment by ArnavVarshney** [comment]
@dyve Any updates?

**Comment by dyve** [comment]
Fixing the issues with 2.0.0 first, then I look at this. Not sure if the <br> insert will not have side effects (like when you do not have a label).

**Comment by ArnavVarshney** [comment]
@dyve Sure take your time! By the way, I did try it without the label. Worked normally for me.
