### ISSUE TITLE
2.0.0 is incompatible with Wagtail due to requiring beautifulsoup v4.9.1

### ISSUE THREAD

**Issue by yhoiseth** [zostera/django-bootstrap4#216]
Hi,

Thanks a ton for your work on django-bootstrap4 — I find it really elegant and useful. And congrats on the 2.0.0 release 🥳 

In a Wagtail (2.9) project, I tried updating all our packages using `pipenv update`. I then got:

```
ERROR: Could not find a version that matches beautifulsoup4<4.9,<5.0.0,>=4.8,>=4.9.1
```

As far as I can tell, this is because Wagtail requires `beautifulsoup4>=4.8,<4.9` (both [in 2.9](https://github.com/wagtail/wagtail/blob/2.9/setup.py#L32) and [in master](https://github.com/wagtail/wagtail/blob/master/setup.py#L32)), while django-bootstrap4 [requires `beautifulsoup4 = "^4.9.1"`](https://github.com/zostera/django-bootstrap4/blob/master/pyproject.toml#L37).

I can see two possible solutions:

1. Allow beautifulsoup4 4.8 in django-booststrap4.
2. Allow beautifulsoup4 4.9 in Wagtail.

It is not obvious to me which solution would be better.

**Comment by dyve** [comment]
I think django-bootstrap4 should set low demands for external packages, so I'll try and fix it on this side.

**Comment by yhoiseth** [comment]
Great! 

FYI, I found the reasoning behind Wagtail’s versioning constraint in https://github.com/wagtail/wagtail/pull/5817#issuecomment-584580715:

> Given that our usage of beautifulsoup is pretty sensitive to breaking changes, I'm wary of including 4.9 and above in the range, so I'll go ahead and set it to `>=4.8,<4.9`.

CC @gasman

**Comment by dyve** [comment]
Fixing in https://github.com/zostera/django-bootstrap4/tree/feature/201
