### ISSUE TITLE
pipenv error with beautifullsoup version and coderedcms

### ISSUE THREAD

**Issue by parleweb** [zostera/django-bootstrap4#218]
It seems the new version requirement for beautifullsoup broke the compatibility with coderedcms and wagtail as it stop at version 4.8.
Using version 1.1.0 is fine.

Pipfile working :
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django-bootstrap4 = "==1.1.0"
coderedcms = "*"

[requires]
python_version = "3.8"
```

Without, it broke.

**Comment by dyve** [comment]
Hi there, please see #216 (fixed in 2.0.1) for Wagtail compatibility regarding beautifulsoup4.

I also see that coderedcms support Django 2.1 and Python 3.5. We have dropped support for both in the 2.0.0 release.

**Comment by vsalvino** [comment]
Hey @dyve - I am curious why Python 3.5 support was dropped, when Python 3.5 is not yet end of life?

Within the Django and Wagtail ecosystems, most maintainers follow the official Python support schedule (https://devguide.python.org/#status-of-python-branches) which really helps keep all of the packages working together. It would be great of django-bootstrap4 could follow the same schedule in the future. I realize this takes additional effort, and would be happy to help with development to see that Python 3.6 does not also get support dropped prematurely. Let me know if I can be of help.

**Comment by dyve** [comment]
Hi @vsalvino, thanks for asking. The reason was basically laziness on my part, and the feedback I got for dropping 3.5 a few months early was enough to convince me that this was a bad call.

**Comment by vsalvino** [comment]
Such is the burden of having a popular package! Thanks for the feedback.
