### ISSUE TITLE
Jinja2 support

### ISSUE THREAD

**Issue by jpic** [zostera/django-bootstrap4#22]
Helllo !

Nice app !

Do you have any plan to support jinja2 backend ?

Thanks !

**Comment by jieter** [comment]
@jpic not really, but we are welcoming well tested pull request adding such behavior.

**Comment by jpic** [comment]
I could get enough in jinja2 for my forms with [this configuration]( https://github.com/yourlabs/crudlfap/blob/master/src/crudlfap_example/settings.py#L100-L102).

Keep up the great work,
<3
