### ISSUE TITLE
Dev dependencies look like they are being installed

### ISSUE THREAD

**Issue by countermeasure** [zostera/django-bootstrap4#222]
When I install in a brand new virtualenv:

    $ pip install django-bootstrap4

I see what look like development dependencies being brought in:

    ...

    Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Pygments-2.6.1 alabaster-0.7.12 asgiref-3.2.9 babel-2.8.0 beautifulsoup4-4.9.1 certifi-2020.4.5.2 chardet-3.0.4 django-3.0.7 django-bootstrap4-2.1.0 docutils-0.16 idna-2.9 imagesize-1.2.0 importlib-metadata-1.6.1 packaging-20.4 pyparsing-2.4.7 pytz-2020.1 requests-2.24.0 six-1.15.0 snowballstemmer-2.0.0 soupsieve-2.0.1 sphinx-3.1.1 sphinx-rtd-theme-0.4.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 sqlparse-0.3.1 urllib3-1.25.9 zipp-3.1.0

I think this is new behaviour with version 2.1.0.

Cheers!

**Comment by dyve** [comment]
Thanks. Might be to do with the Poetry configuration for readthedocs. Can you confirm 2.0.x did not have this issue for you?

**Comment by W1ldPo1nter** [comment]
Since I've just stumbled into the same problem, I can confirm that this doesn't happen when installing 2.0.1.

I also took a look into the `PKG-INFO` file of the sdist-Package of 2.1.0 on PyPI, which shows the problem:
```
Provides-Extra: docs
Requires-Dist: beautifulsoup4 (>=4.8.0,<5.0.0)
Requires-Dist: django (>=2.2,<4.0)
Requires-Dist: importlib-metadata (>=1.5.0,<2.0.0); python_version < "3.8"
Requires-Dist: m2r (>=0.2.1,<0.3.0); extra == "docs"
Requires-Dist: sphinx (>=2.4,<3.0); extra == "docs"
Requires-Dist: sphinx_rtd_theme (>=0.4.3,<0.5.0)
```

The `extra == "docs"` marker is missing for `sphinx_rtd_theme`, which leads to the addition of the whole Sphinx requirements chain even if the `docs` feature is not being installed.

**Comment by dyve** [comment]
Found the cause, thanks. Typo in `pyproject.toml`.

**Comment by countermeasure** [comment]
Fast work! Thanks.
