### ISSUE TITLE
Upgrade To Bootstrap 5

### ISSUE THREAD

**Issue by 9mido** [zostera/django-bootstrap4#224]
https://v5.getbootstrap.com/

https://github.com/twbs/bootstrap/projects

Better to start early then to wait till the last minute.

Probably need to rename this package when fully upgraded or make another branch.

**Comment by laoshaw** [comment]
yes now beta is out, can't wait

**Comment by bsolomon1124** [comment]
An entirely new package would probably be appropriate considering that https://github.com/zostera/django-bootstrap3 and https://github.com/zostera/django-bootstrap4 exist separately.

**Comment by jeriox** [comment]
somebody already forked this to https://github.com/zelenij/django-bootstrap-v5

Sadly the only thing that has been changed was the version number, especially the form rendering is broken with the changes introduced in v5. Are there any plans to create a new package?

**Comment by xi** [comment]
I toyed around with bootstrap 5 in a hobby project (https://github.com/xi/django-bs4/commit/bce484686901d5ed7937dc1a3b5d7c180e72f717). Maybe the information I gathered is helpful to migrate this library, too. The most relevant changes are:

- `form-group` was replaced by `mb-3`
- new class `form-label`
- new class `form-select` that replaces `form-control` for selects
- `form-control-file` was replaced by `form-control`
- `input-group-prepend` and `input-group-append` are no longer necessary
- `form-text` has different styling (`<small class="form-text text-muted">` should be replaced by `<div class="form-text">`)

**Comment by svenhertle** [comment]
I wanted to start the migration of the module from 4 to 5 today (https://github.com/svenhertle/django-bootstrap5) and ideally contributing  the code for zostera/django-bootstrap5.

But I noticed that @dyve is working on another django-bootstrap repo (https://github.com/zostera/django-bootstrap). Could you or someone else at Zostera maybe give us a short update about your further plans with this module?

I would like to avoid several forks of this module on PyPI ;)

**Comment by dyve** [comment]
Thanks Sven. I’ll clarify after the weekend.

**Comment by dyve** [comment]
@svenhertle and others, here are my current thoughts on the django-bootstrap projects

In the long run, we see that we repeat a lot of work, especially on the forms section, between versions of `django-bootstrapX`. You could even say that the package is mostly a form renderer, and everything else comes second. The weak spot here is that Django has a closed API for form rendering. Its own templates get more data than what is exposed to the outside. This is what I've been investigating on https://github.com/zostera/django-bootstrap, and what @xi has been investigating on https://github.com/xi/django-bs4. This is basically a smarter "Django formsets, forms, fields and widget rendering using templates" that has Bootstrap as the prime target. For me, this is also something that could be improved in django itself (think `{% render_form form "folder/my-form_template.html" %}`.

Another line of thinking is that we have the popular package https://github.com/django-crispy-forms/django-crispy-forms that can handle forms and bootstrap 2, 3 and 4 (and 5 coming up). I have never worked with crispy forms myself, but it would be a shame to have 2 popular packages working on the same problem. That's also something worth investigating.

For now, and for a graceful migration of `django-bootstrap3` and `django-bootstrap4`, I'd welcome a `django-bootstrap5` package. We have reserved the names on PyPI, readthedocs and in our repo. @svenhertle I'd be happy to give you access to start the port.

**Comment by svenhertle** [comment]
Thanks for the update and explanations!

I also never worked with crispy forms, may be a good idea for new projects.

The Bootstrap migration from 4 to 5 seems to be easier than 3 to 4. I will get back when i have a basic working version!

**Comment by dyve** [comment]
Thanks! I have also filed a ticket at Django to make forms integration easier.

https://code.djangoproject.com/ticket/32541

**Comment by shawnngtq** [comment]
Maybe out of scope, but I do love to see if it's possible to have integration for mdbootstrap 😁

**Comment by dyve** [comment]
@svenhertle https://github.com/zostera/django-bootstrap5 (work in progress)

**Comment by dyve** [comment]
Version 1.0.0 of https://github.com/zostera/django-bootstrap5 has been released.
