### ISSUE TITLE
Icons didint changed. There is a easy way to do that?

### ISSUE THREAD

**Issue by matttheus** [zostera/django-bootstrap4#230]
![image](https://user-images.githubusercontent.com/30329820/90186230-3acf9a80-dd8e-11ea-92f1-67e3f028f564.png)

Here is the code:

![image](https://user-images.githubusercontent.com/30329820/90186942-62733280-dd8f-11ea-906a-73f036eed076.png)

When occur some error in the form, I wanna change the icon

**Comment by dyve** [comment]
Interesting, the success class appears because the field have no errors, but the form itself does.

**Comment by dyve** [comment]
See #276. For this particular issue, the behavior is actually correct. The fields are marked as having no issues, yet the form does have errors at the form level.
