### ISSUE TITLE
# Include BOOTSTRAP4_FOLDER in path

### ISSUE THREAD

**Issue by winner106** [zostera/django-bootstrap4#231]
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ""))

# Include BOOTSTRAP4_FOLDER in path
BOOTSTRAP4_FOLDER = os.path.abspath(os.path.join(BASE_DIR, "..", "bootstrap4"))
if BOOTSTRAP4_FOLDER not in sys.path:
    sys.path.insert(0, BOOTSTRAP4_FOLDER)

hi,thanks very much for sharing this project~
i have this question:
why folder → "bootstrap4" do not insert? but seems it runs well~
is that a problem?

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
