### ISSUE TITLE
Update to Bootstrap 4.5.2

### ISSUE THREAD

**Issue by paulschreiber** [zostera/django-bootstrap4#233]

**Comment by modernlearner** [comment]
The code is pointing to 4.5.2: https://github.com/zostera/django-bootstrap4/blob/main/src/bootstrap4/bootstrap.py#L7-L12

The latest version, however, is 4.5.3.

**Comment by dyve** [comment]
It's not at 4.6.0, thanks for your bug report and for your patience.
