### ISSUE TITLE
warning in django logs loading bootstrap css

### ISSUE THREAD

**Issue by fcoppey** [zostera/django-bootstrap4#235]
Every click on my django website generates this warning in the logs although all seem to work properly. any idea why?

```
WARNING 2020-10-13 09:34:58,954 log Not Found: /samples/{'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T', 'crossorigin': 'anonymous'}
WARNING 2020-10-13 09:35:02,974 log Not Found: /samples/14020/{'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T', 'crossorigin': 'anonymous'}
WARNING 2020-10-13 09:35:05,849 log Not Found: /samples/{'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T', 'crossorigin': 'anonymous'}
WARNING 2020-10-13 09:35:19,045 log Not Found: /samples/13263/{'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T', 'crossorigin': 'anonymous'}
```

**Comment by dyve** [comment]
Somehow you have the wrong integrity.

Your config:
'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T'
'crossorigin': 'anonymous'

Proper config:
href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous"

This would be something in your settings or templates, the (current) `django-bootstrap4` uses Bootstrap 4.5.2.

**Comment by fcoppey** [comment]
I have updated to django-bootstrap4==2.3.0

And the problem persists with this new config :


BOOTSTRAP4_DEFAULTS = {
    "css_url": {
        "href": "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css",
        "integrity": "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z",
        "crossorigin": "anonymous",
    },


Problem could come from somewhere else?

On 13 Oct 2020, at 09:52, Dylan Verheul <notifications@github.com<mailto:notifications@github.com>> wrote:



Somehow you have the wrong integrity.

Your config:
'href': 'https:/stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'<http://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
'integrity': 'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T'
'crossorigin': 'anonymous'

Proper config:
href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous"

This would be something in your settings or templates, the (current) django-bootstrap4 uses Bootstrap 4.5.2.
