### ISSUE TITLE
Update example README

### ISSUE THREAD

**Issue by ktechmidas** [zostera/django-bootstrap4#239]
No idea how to use poetry, but the example README (https://github.com/zostera/django-bootstrap4/blob/main/example/README.md) told me I could simply run a pip install -r requirements.txt which fails ... I'll just checkout the old one with a working setup.py for now, but can we get some updated instructions?

> pip install -r requirements.txt
>ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/monotoko/django-bootstrap4 (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by dyve** [comment]
Thanks for reporting this, that needs fixing.

**Comment by Sarcastic-Pharm** [comment]
FWIW, the readme instructions work perfectly for me? Windows 10, Python 3.8, fresh venv.

**Comment by dyve** [comment]
This was one of the reasons for dropping poetry. Should work now.
