### ISSUE TITLE
After installing bootstrap get error with version of SQLite

### ISSUE THREAD

**Issue by NeasaNiA** [zostera/django-bootstrap4#243]
I ran Sudo pip install django-bootstrap4
And now I’m getting an error with the version of SQLite
File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
