### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by dfrankow** [zostera/django-bootstrap4#254]
Thanks for your work on this project.

https://django-bootstrap4.readthedocs.io/en/latest/ has a changelog that stops at 2.0.1, then "UNRELEASED".

https://github.com/zostera/django-bootstrap4/blob/main/CHANGELOG.md shows latest version is 2.3.2 (in dev), and installing from pypi gives 2.3.1.

So, readthedocs is out of date. Something should be updated.

**Comment by thomwiggers** [comment]
readthedocs still links to the `master` branch. Presumably it needs to be updated to build the docs from the `main` branch.
