### ISSUE TITLE
Release 0.0.2 on pypi?

### ISSUE THREAD

**Issue by nikolas** [zostera/django-bootstrap4#26]
It seems only 0.0.1 is available on pypi: https://pypi.python.org/pypi/django-bootstrap4

Note that this process can be automated with travis:
* https://docs.travis-ci.com/user/deployment/pypi/
* e.g.: https://github.com/ccnmtl/django-pagetree/blob/master/.travis.yml#L24

**Comment by jieter** [comment]
Yes, you are right, hopefully we'll be able to do that tomorrow

**Comment by jieter** [comment]
Apparently, I'm not allowed to upload django-bootstrap4 on pypi yet, I'll report back if it's fixed, probably monday.

**Comment by jieter** [comment]
released [0.0.3](https://pypi.python.org/pypi/django-bootstrap4/0.0.3)
