### ISSUE TITLE
Explain how to do theming with django-bootstrap4

### ISSUE THREAD

**Issue by dfrankow** [zostera/django-bootstrap4#260]
Thanks for your work on this project.

https://getbootstrap.com/docs/4.6/getting-started/theming/ describes how to modify the Bootstrap theme. They say:

- _"theming is accomplished by Sass variables, Sass maps, and custom CSS"_
- _"[If you don't use npm] in your custom.scss, you’ll import Bootstrap’s source Sass files"_

I'm not sure how to do that with django-bootstrap4.

Is there a way to theme using this project, or would I have to get my own bootstrap files instead?

I'm not asking for a feature here, just an explanation of what the current state of the world is.

**Comment by dyve** [comment]
Basically, you do not use the `{% bootstrap_css %}` tag, but instead you make and import your own CSS.

**Comment by dfrankow** [comment]
I see. So implement our own bootstrap CSS, but could still use other tags if we wished (e.g., bootstrap_javascript, bootstrap_messages, ..)?

**Comment by dfrankow** [comment]
I wonder how that interacts with a CDN. I assume I can download bootstrap SASS, inherit and modify as directed, but in production serve the bootstrap CSS from a CDN, and only our mods from our servers.

But, that is not a django-bootstrap4 question, it's more about serving up a themed bootstrap.

**Comment by dyve** [comment]
No @dfrankow, you'd also serve a modified Bootstrap in production. But this is becoming something more suited to stackoverflow.com, I'm sure you'll get your answers there.
