### ISSUE TITLE
help-block class for form fields does not exist anymore

### ISSUE THREAD

**Issue by alvarovelezgalvez** [zostera/django-bootstrap4#29]
According to [Bootstrap 4 docs](https://getbootstrap.com/docs/4.0/components/forms/#help-text) this class does not exist anymore and must be replaced by `form-text text-muted`

Regards!

**Comment by Dulcin** [comment]
I can confirm this. Would like to see this fixed!

**Comment by jproffitt** [comment]
I have made an PR for this: https://github.com/zostera/django-bootstrap4/pull/39

**Comment by jieter** [comment]
Just released [0.0.5](https://pypi.python.org/pypi/django-bootstrap4/0.0.5), including the fix for #39
