### ISSUE TITLE
What Python versions should we target?

### ISSUE THREAD

**Issue by FlipperPA** [zostera/django-bootstrap4#3]
Should we target Python 3.4+ only? Or 2.7 and 3.4+?

Django currently supports 2.7 and 3.4+, however, v2.0 which will be released towards the end of the year will be Python 3 only, and I bet it'll beat Bootstrap 4 into general release.

**Comment by dyve** [comment]
Django 1.11 supports 2.7 and is aan LTS release. Let's not shut that combination out.

**Comment by FlipperPA** [comment]
That's what I assumed - thanks for the confirmation! So far I've targeted 2.7 and 3.4+.
