### ISSUE TITLE
Bootstrap v3's label.control-label is now label.form-control-label

### ISSUE THREAD

**Issue by danickinator** [zostera/django-bootstrap4#30]
As per the title, it looks as if the form classes have had a few name changes in v4.

What was `.control-label` is now `.form-control-label`.

Bootstrap 4 Docs reference: https://getbootstrap.com/docs/4.0/components/forms/#form-groups

**Comment by jieter** [comment]
@danickinator thanks for reporting. Are you able to compose a patch and open a pull request making this change?
