### ISSUE TITLE
Update "latest" label to latest release

### ISSUE THREAD

**Issue by louispotok** [zostera/django-bootstrap4#302]
Hi, small note - it looks like v 1.1.0 (Dec 9 2019) is still labeled as the "Latest" release, which means it shows up on the GH repo homepage as the latest version. Found that a bit confusing before clicking into the releases list and seeing all the work since then.

**Comment by dyve** [comment]
Thanks, will look into it!

**Comment by dyve** [comment]
I fixed it by editing the tag manually.
