### ISSUE TITLE
set_placeholder: How to have different for different forms

### ISSUE THREAD

**Issue by sant527** [zostera/django-bootstrap4#303]
I want to have `'set_placeholder': False`, for one form and for another i want `'set_placeholder': True`

How can i do this

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
