### ISSUE TITLE
Docs still use "django-bootstrap3"

### ISSUE THREAD

**Issue by rixx** [zostera/django-bootstrap4#31]
Docs still use `django-bootstrap3` everywhere, for example in installation instructions.

(Are you interested in PRs here?)

**Comment by rixx** [comment]
This is fixed in `develop`, but readthedocs appears to build off `master`.

**Comment by FlipperPA** [comment]
We're overdue for a merge party. :)

**Comment by dyve** [comment]
We're looking at the docs, also because the docs URL was/is claimed by another party :-(

**Comment by dyve** [comment]
We hope to have access to the preferred ReadTheDocs name soon, a little more patience.

**Comment by dyve** [comment]
The documentation is now (also) at http://django-bootstrap4.readthedocs.io/.

We've had great help from ReadTheDocs and @FlipperPA to make this happen. Thanks!
