### ISSUE TITLE
pip install bootstrap4 error.

### ISSUE THREAD

**Issue by Vialelin** [zostera/django-bootstrap4#315]
command in virtual environment - 'pip install django-bootstrap4'
_Error_
ImportError: cannot import name 'SCHEME_KEYS' from 'pip._internal.models.scheme' (c:\users\chawa\onedrive\desktop\learning_log\ll_env\lib\site-packages\pip\_internal\models\scheme.py)

Python version - 3.8.5
Django version - 3.2.4

Not sure how to handle this error, trying to install bootstrap4

**Comment by bastiaan85** [comment]
This is a pip issue, not a django-bootstrap4 issue. Also see https://stackoverflow.com/questions/68221302/receiving-an-error-when-installing-bootstrap4
