### ISSUE TITLE
bootstrap_css_url is broken

### ISSUE THREAD

**Issue by nikolas** [zostera/django-bootstrap4#33]
According to the [docs](http://django-bootstrap4.readthedocs.io/en/latest/templatetags.html#bootstrap-css-url), `bootstrap_css_url` returns the bootstrap CSS url.

In django-bootstrap3, my templates include the bootstrap URL like this:

    <link href="{% bootstrap_css_url %}" rel="stylesheet">

In django-bootstrap4 0.0.3, that breaks, yielding:

    <link href="{&#39;crossorigin&#39;: &#39;anonymous&#39;, &#39;integrity&#39;: &#39;sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M&#39;, &#39;href&#39;: &#39;https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css&#39;}" rel="stylesheet">

**Comment by nikolas** [comment]
Hmm, I just saw issue #9 - it looks like you're considering removing these template tags anyways. I'm fine with that, and in that case we should just go ahead and remove them, and clarify the installation instructions to note that you need to include these yourself in the template.

**Comment by FlipperPA** [comment]
@nikolas I believe we're going to keep the template tags, as they're a very friendly way for getting newcomers started; I'll take a look at CSS next. The JavaScript ones have been merged but not published to PyPI yet: https://github.com/zostera/django-bootstrap4/pull/44

**Comment by jieter** [comment]
released [0.0.5](https://pypi.python.org/pypi/django-bootstrap4/0.0.5) which also contains #44.
