### ISSUE TITLE
Upgrade importlib_metadata

### ISSUE THREAD

**Issue by rixx** [zostera/django-bootstrap4#380]
This library currently enforces importlib_metadata<3 for Python<3.8. This causes conflicts for us, since other libraries such as markdown start enforcing importlib_metadata>4.4 to get Python-3.10-like behaviour.

Is there a specific reason this version is enforced to be <3?

**Comment by tswfi** [comment]
Just got the same problem on one of our projects.

**Comment by dyve** [comment]
Fixed in #604
