### ISSUE TITLE
Bootstrap4 is not loaded on Django admin template

### ISSUE THREAD

**Issue by ShuntaH** [zostera/django-bootstrap4#428]
I've tried to load bootstrap4 in the following way. (https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html)

###################
Django 3.2.9
django-bootstrap4 21.1
###################

It can work but it does not work on templates which is extended from admin/base_site.html.

<img width="330" alt="extended-not-admin" src="https://user-images.githubusercontent.com/30917236/152637139-53fc8613-dec7-4697-a679-ce01f20ed535.png">

<img width="727" alt="chrome-console-other" src="https://user-images.githubusercontent.com/30917236/152637155-b3c6dca2-0aba-4013-8e42-326c5420dc29.png">

The above example works.

<img width="482" alt="extended-admin" src="https://user-images.githubusercontent.com/30917236/152637219-a54093e8-6c3a-45e6-898c-86dd879d1783.png">

<img width="734" alt="chrome-console-admin" src="https://user-images.githubusercontent.com/30917236/152637223-32beb381-6b17-498c-8984-587261d3753b.png">

However, the above case does not work.
{% load bootstrap4 %} is loaded successfully because I got error if I removed bootstrap4 from INSTALLED_APPS on settings.py.

Is this error or expected behavior?

**Comment by ytyng** [comment]
@ShuntaH 
Can you write 
```
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
```
into `{% block extrahead %} 〜 {% endblock %}` ?

**Comment by ShuntaH** [comment]
I've solved it. It works now. Thank you so much.
if origin html files have these tags, I realized that I don't have to load anymore.
and I don't have to write these tags in extrahead block on origin html files. otherewise i have to write these in extrahead block.
