### ISSUE TITLE
bootstrap_jquery_url template tag calls slim version of jQuery

### ISSUE THREAD

**Issue by FlipperPA** [zostera/django-bootstrap4#43]
The template tag `{% bootstrap_jquery_url %}` currently calls the **slim** version of jQuery, which doesn't support quite a few features of the full jQuery version. See here:

https://github.com/zostera/django-bootstrap4/blob/master/bootstrap4/bootstrap.py#L19

I'm happy to issue a P.R. to include the full version of jQuery, but it raises the question of which direction to head:

Option (1): make the existing template tag point to the full version.
Option (2): make the existing template tag point to the full version, and add another template tag called `{% bootstrap_jquery_slim_url %}`
Option (3): add a template tag called `{% bootstrap_jquery_full_url %}` that points to the full version.

`django-bootstrap3` currently points to the full version of jQuery.

Thoughts?

**Comment by dyve** [comment]
Option (4): Add jquery=falsy|slim|full (default=full) to the tag
falsy = no jquery
slim = slim jquery
full = full jquery (default)

This should also be passed on from the ``bootstrap_js`` template tag

**Comment by FlipperPA** [comment]
P.R. issued: https://github.com/zostera/django-bootstrap4/pull/44

Thanks, as alawys, @dyve!

**Comment by FlipperPA** [comment]
...and I just noticed that there was a final line to your message that wasn't on my secondary monitor! Another P.R. will be coming soon for the `bootstrap_javascript` tag.

**Comment by FlipperPA** [comment]
This has been address with https://github.com/zostera/django-bootstrap4/pull/44

Thank you!
