### ISSUE TITLE
it seems bootstrap4 do not use correctly ,can anyone tells me why it shows like this

### ISSUE THREAD

**Issue by sfitstest** [zostera/django-bootstrap4#45]

**Comment by sfitstest** [comment]
django-bootstrap4
home formset form form_by_field form_horizontal form_inline form_with_files pagination miscellaneous

× hello http://example.com
This is bootstrap4 for Django.

**Comment by dyve** [comment]
It looks like CSS/JS aren't loading. You can check this in your browser (enable developer tools).

**Comment by sfitstest** [comment]
how can i check it,can you tell me more details,I just download the project and go to demo,and excuete python manage.py runserver,should i configure something?thank you

**Comment by dyve** [comment]
Google for "javascript debugging", what you should check is if you JS and CSS files are loading.
Example start site:
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript

If you need assistance getting up and running, this is not the place to ask. Instead, ask your question on StackOverflow.com.

Closing this issue! Good luck.
