### ISSUE TITLE
How to change field_class of input (not the CSS class of the div that wraps the field)

### ISSUE THREAD

**Issue by Staff-i** [zostera/django-bootstrap4#47]
How change the field_class of input for use readonly plain text class "form-control-plaintext" ?

https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text

**Comment by sebastianjungels** [comment]
Was this issue ever solved? I have a similar issue where bootstrap does not pass the field_class to HTML. My code is:

{% bootstrap_field form.username field_class="field" placeholder="Logon" show_label=False %}

but the HTML / CSS class renders "form-control".

**Comment by SvenMoenig** [comment]
taken from https://docs.djangoproject.com/en/2.2/ref/forms/widgets/

**you can set the django-widget's css-class:**

```python
class MyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'field'})

    class Meta:
        model = MyModel
        fields = ['some_other_field', 'username']
```

then your template-code should work:

> {% bootstrap_field form.username placeholder="Logon" show_label=False %}

**Comment by rabbagliettiandrea** [comment]
it's so cumbersome :/
