### ISSUE TITLE
Unproperly use of help block

### ISSUE THREAD

**Issue by nunesvictor** [zostera/django-bootstrap4#48]
Hi there,

I notice that help block still uses bootstrap3 implementation, but it not works properly with bootstrap4. See the JSFiddle https://jsfiddle.net/rm2Lmxqq/

django-bootstrap4 uses help block implementation to highlight the field error, but with the current issue the field isn't highlighted, just has a common text below it.

Change the help block implementation to the bootstrap4 standard sure will take care of it.

**Comment by jieter** [comment]
Is this fixed by #39 ?

**Comment by nunesvictor** [comment]
yeah, actually I send a pull request it solves the problem, you can see it here: #49
I install the package from source after the merge and it works. I think we can close this issue for now.

**Comment by jieter** [comment]
I'm sorry, missed the connection. quick tip: add `fixes #48` to your commit message or pull request description and github will automatically close the issue for you (apart from the fact it provides context for other readers).
