### ISSUE TITLE
Add goals etc. to README

### ISSUE THREAD

**Issue by dyve** [zostera/django-bootstrap4#5]
I suggest we add a few goals and policies to the README. Mainly this:

- We aim to support what is in Bootstrap 4.
- Anything not natively part of Bootstrap 4 will not be accepted into `django-bootstrap4`, but plugins are welcome.

The reason for this is that I've seen a lot of cool PR's and suggestions for `django-bootstrap3` that enable `table` based views, date pickers, et cetera. It would be good that people know that the goal of the app is limited to Bootstrap 4.

**Comment by FlipperPA** [comment]
That makes a lot of sense. I work with Wagtail a fair amount, and write add-ons for it as well. Perhaps we take a similar tact and start an example extension, such as `django-bootstrap4-datepicker`, which also contain the appropriate JS/CSS assets and template tags with the Django app?

**Comment by dyve** [comment]
Do you have an example of another package that uses the template solution?
