### ISSUE TITLE
Customising form classes

### ISSUE THREAD

**Issue by ChaosCA** [zostera/django-bootstrap4#50]
Hi,

I wasn't able to find it in the documentation, how can I change what classes a Django form element uses?

Thanks

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap4`, we'll be happy to reply over there!
