### ISSUE TITLE
Django bootstrap4 uses bootstrap4 beta2?

### ISSUE THREAD

**Issue by kamranhossain** [zostera/django-bootstrap4#55]
Is it Django bootstrap4 uses bootstrap4 beta2?

**Comment by FlipperPA** [comment]
As you can see here, the latest from master is on Bootstrap 4:

https://github.com/zostera/django-bootstrap4/blob/master/bootstrap4/bootstrap.py#L13

Version `0.0.4` includes these changes.

**Comment by jieter** [comment]
1916275 upgrades bootstrap to beta.3, not released yet.
