### ISSUE TITLE
Help text for form fields

### ISSUE THREAD

**Issue by sunpig** [zostera/django-bootstrap4#57]
Bootstrap 4 uses a combination of `.form-text` and `.text-muted` to replace the old `.help-block` class for specifying help text on form elements. PR #49 makes this change in the django-bootstrap4 project code, but it keeps the help text in a `<div>` element, whereas the Bootstrap docs use a `<small>` instead (https://getbootstrap.com/docs/4.0/components/forms/#help-text), which renders smaller text.

The lack of a semantic classname (`.help-block` was great) makes it harder to isolate and target help text but it's still possible. `.form-group .form-text.text-muted {font-size: 80%}` works for me, but I wonder if it would be better to change the `field_help_text_and_errors.html` [template](https://github.com/zostera/django-bootstrap4/blob/master/bootstrap4/templates/bootstrap4/field_help_text_and_errors.html) to render a `<small>` instead of a `<div>`, so that a `{% bootstrap_field %}` template tag for a field with help text will match what is shown in the Bootstrap examples.

**Comment by jieter** [comment]
@sunpig thanks for the suggestions. I think we're after vanilla bootstrap 4, so if you spot something not conforming to that, please open a PR to fix it!
