### ISSUE TITLE
Form layout

### ISSUE THREAD

**Issue by dyve** [zostera/django-bootstrap4#6]
One of the missing things from `django-bootstrap3` was the ability to layout a form. There were a couple of good attempts and PR's to add form layout through classes, but it never clicked. Some people switched to crispy because of the lack of layout. I don't mind people using crispy, but a little help with organizing a form layout would be nice.

I think this would be a good addition for the future.

**Comment by dyve** [comment]
I realize this might be seen as a contradiction to #5.

**Comment by FlipperPA** [comment]
Bootstrap 4's FlexBox support should make this much easier to accomplish; I'm guessing the lack of math in Django's templates made this a bit tricky. Now that Bootstrap 4 automagically balances columns, layout options should be more straightforward. Unless you're thinking of something else?

**Comment by dyve** [comment]
Doesn't seem relevant anymore, new ticket if we run into this again.
