### ISSUE TITLE
Breaking changes in bootstrap4 beta3

### ISSUE THREAD

**Issue by y-spreen** [zostera/django-bootstrap4#61]
Please address the breaking changes in beta 3.  
https://getbootstrap.com/docs/4.0/migration/#beta-3-changes

One example would be the addons which changed a lot.

> Input group addons are now specific to their placement relative to an input. We’ve dropped .input-group-addon and .input-group-btn for two new classes, .input-group-prepend and .input-group-append. You must explicitly use an append or a prepend now, simplifying much of our CSS.

**Comment by jieter** [comment]
@nO-OnE-910 thanks for bringing this up. You are welcome to open pull requests!

**Comment by nO-OnE-910** [comment]
Since the fix was very time-sensitive for me, I found a workaround for my project. So its sadly not a priority for me anymore. I will surely look into it when I have some time, but I guess someone else — who has a bigger interest in it — will have done it by then..

**Comment by JonathanSeguin** [comment]
There is a currently PR waiting for merge addressing these issues
https://github.com/zostera/django-bootstrap4/pull/63

**Comment by dyve** [comment]
Fixed with #63 - thanks all!
