### ISSUE TITLE
boostrap_icon within buttons expects endbuttons

### ISSUE THREAD

**Issue by mweinelt** [zostera/django-bootstrap4#62]
```jinja
<div class="panel panel-default">
    <div class="panel-heading">
        Edit Device
    </div>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "floppy-save" %} Save
        </button>
        <button type="reset" class="btn btn-primary">
            {% bootstrap_icon "repeat" %} Reset
        </button>
        {% endbuttons %}
    </form>
</div>
```

results in 
> TemplateSyntaxError at /device/edit/56
> Invalid block tag on line 31: 'bootstrap_icon', expected 'endbuttons'. Did you forget to register or load this tag?

The offending line is 
```
            {% bootstrap_icon "floppy-save" %} Save
```

**Comment by diogosimao** [comment]
The same happens with me. Just about after adding that lines to include the icon.

**Comment by ilg** [comment]
I think this isn't because of using it inside buttons, but because `bootstrap_icon` doesn't exist.  From https://github.com/zostera/django-bootstrap4/blob/master/HISTORY.rst, toward the bottom:

> Remove bootstrap_icon, BS4 no longer has default icons.

**Comment by diogosimao** [comment]
I see. Well... the option the suits me just fine is django-bootstrap4 plus [django-icons](https://github.com/zostera/django-icons)
```
{% bootstrap_form form %}
{% buttons %}
    <button type="submit" class="btn btn-primary btn-custom">
    {% icon 'search' %}{% trans 'Debt search' %}
    </button>
{% endbuttons %}
```

**Comment by dyve** [comment]
👍 please use https://github.com/zostera/django-icons for icons :-)
