### ISSUE TITLE
Update for 4 final?

### ISSUE THREAD

**Issue by KrunchMuffin** [zostera/django-bootstrap4#65]
Will this be updated for BS4 final any time soon? Just curious. Would like to use it.

**Comment by AJerm** [comment]
Also interested in a timeline for this before I start a new project, thanks

**Comment by mattfox** [comment]
See #66

**Comment by dyve** [comment]
Working on it. PR's to speed up the process are welcome.

**Comment by jieter** [comment]
released [0.0.6](https://pypi.python.org/pypi/django-bootstrap4/0.0.6)
