### ISSUE TITLE
Template tags and filters docs broken

### ISSUE THREAD

**Issue by suspiciousRaccoon** [zostera/django-bootstrap4#667]
The documentation page for Template tags and filters is broken in the docs 
![image](https://github.com/zostera/django-bootstrap4/assets/127566947/374f1c09-9df8-4245-a99e-dde137c62160)

**Comment by ianastewart** [comment]
Until this is fixed you can find the documentation for each tag in bootstrap4.py.

**Comment by dyve** [comment]
Fixed with new Read the Docs config.
