### ISSUE TITLE
Template does not exist

### ISSUE THREAD

**Issue by alerodrom** [zostera/django-bootstrap4#73]
I'm triying to use `django-bootstrap4` in my project but I have a problem. If I send a form with errors when the view go to render fail.  The project  try to load a template but he doesn't find it, the template is `bootstrap4/field_help_text_and_errors.html`.

I follow the guide to use this but I don't have any idea that i'm making bad. I need to download the template and add this templates to my project? 

Thanks and sorry for my english!

![issue](https://user-images.githubusercontent.com/14248341/37413342-1f0e4624-27a7-11e8-996b-8d3dbcb77b48.jpg)

**Comment by FlipperPA** [comment]
Howdy, welcome to Django and Bootstrap 4! Can you include your TEMPLATES setting from your settings file, and have you added `bootstrap4` to your `INSTALLED_APPS` list in settings?

**Comment by dyve** [comment]
Hi @alerodrom! It looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). Please try to get your answer there. If you use tag `django-bootstrap4`, we'll be happy to answer over there.
