### ISSUE TITLE
[Question] Pagination

### ISSUE THREAD

**Issue by bukowa** [zostera/django-bootstrap4#80]
````python
{% bootstrap_pagination page_obj url={{ request.path }} %}
````
I need pagination to work with GET queries how do i do that?
I have this query:
````
?title=&category=&age=&gender=female
````
But urls in pagination shows only:
````
/?page=1
````

**Comment by dyve** [comment]
Hi, does this help:

https://github.com/zostera/django-bootstrap4/blob/master/demo/demo/templates/demo/pagination.html

**Comment by bukowa** [comment]
@dyve Thanks but how do i include all of the query parameters in the "extra" tag? I mean, how can i include any variable in the parameter?
````python
 {% bootstrap_pagination lines url="{{ variable}} extra="{{ variable }}" %}
````
This does not work.

**Comment by dyve** [comment]
Try something like
`{% bootstrap_pagination lines url="foo/bar?thing="|add:variable %}`

**Comment by bukowa** [comment]
@dyve thank you here is my solution:
````python
get_copy = self.request.GET.copy()
context['parameters'] = get_copy.pop('page', True) and get_copy.urlencode()
````
````
{% bootstrap_pagination page_obj extra=""|add:parameters %}
````

**Comment by jieter** [comment]
seems to be resolved, so closing.
