### ISSUE TITLE
Problem loading svg files from s3

### ISSUE THREAD

**Issue by Ballpin** [zostera/django-bootstrap4#85]
Hi,
Im getting a error when django tries to load icons.svg from aws s3.
The error i get is _"Unsafe attempt to load URL <URL> from frame with URL <URL>. Domains, protocols and ports must match."_ 

Its trying to load from https://bucket_name.s3.amazonaws.com/static/djangocms_bootstrap4/sprites/icons.svg any idea why?

**Comment by dyve** [comment]
Can you show the django-bootstrap4 code that makes this call?

**Comment by Ballpin** [comment]
```
function(e, t, n) {
    "use strict";
    n.d(t, "a", function() {
        return r
    }),
    n.d(t, "b", function() {
        return i
    });
    var r = function(e) {
        var t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : "/static/";
        return '\n    <span class="icon icon-' + e + '" title="' + (arguments.length > 2 && void 0 !== arguments[2] ? arguments[2] : "") + '">\n        <svg role="presentation">\n            <use xlink:href="' + t + "djangocms_bootstrap4/sprites/icons.svg#" + e + '"></use>\n        </svg>\n    </span>'
    }
      , i = function() {
        return '\n    <div class="djangocms-bootstrap4-preview ' + (arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : "") + '">\n        <h2>' + (arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : "Preview") + '</h2>\n        <div class="b4-preview js-preview"></div>\n        <a href="#close" class="b4-close js-close">x</a>\n    </div>\n'
    }

```


Seems to be this part. I red on some articles that webpack is behind this. The best thing is to use [svg-inline-plugin](https://github.com/webpack-contrib/svg-inline-loader). According to the article i read it had something to do that because svg are xml and they are normally unsafe for chrome and other browsers and therefor they will be denied. But if you put it as inline it will let it pass. I tried adding CSP meta tags to the template but it did not help. Now when i think about i probably added the CSP meta tags to the wrong temnplate they should have been in plugin template and not in my base template.

`<svg role="presentation">\n            <use xlink:href="' + t + "djangocms_bootstrap4/sprites/icons.svg#" + e + '"></use>\n        </svg>`

**Comment by Ballpin** [comment]
Thanks @dyve for your answer. Sorry i have been tired lately. I noticed now that i was checking in the wrong repository. This one https://github.com/divio/djangocms-bootstrap4 was the one i was looking for. 

Closing this one.
