### ISSUE TITLE
Tags for including Bootstrap4

### ISSUE THREAD

**Issue by dyve** [zostera/django-bootstrap4#9]
I'm thinking of removing the template tags for inclusion of JS and CSS. When using local source/dist a dev should know what to include, may use webpack or another tool to combine static files, et cetera. So the only viable use case for including through tags would be CDN. This would burden us with keeping up with Bootstrap releases to adjust CDN URL's and signatures.

Any input on this matter?

**Comment by FlipperPA** [comment]
In my work context, you're absolutely right; we combine our Bootstrap files, jQuery and Bootstrap JS and minify (we're still using GULP). However, I do make use of the template tags quite a bit for personal projects out of sheer laziness. They are nice to have for teaching beginners as well. I worked with a fair amount of people new to Django, and it is always a pretty cool moment to take their learning projects and show them "how easy" it is to use Bootstrap by just putting the tags in the template.

I'm not sure if that "nice to have" outweighs the ongoing maintenance of updating... how often does Bootstrap release once the general release drops?

**Comment by dyve** [comment]
I'm on the path of allowing urls as dicts, so `origin` and `integrity` values can be set. Looking good so far.

**Comment by FlipperPA** [comment]
Fantastic, that's a huge win for those of us who have clients with restrictive proxy servers.

**Comment by nikolas** [comment]
These tags are broken in the 0.0.3 release anyways (See #33) - I vote for just removing them, for the reasons you mentioned, and updating the installation docs to reflect that.

**Comment by FlipperPA** [comment]
I know a fair amount of projects actually use these. While I roll my own via SASS, these are fantastic for teaching Django to newcomers when you get to the point of the project where you want to make a site start to look nice. I've done it many times in tutorials!

**Comment by nikolas** [comment]
These are nice shortcuts, but all they do is emit an HTML element, so your tutorials could just replace `{% bootstrap_css_url %}` with the bootstrap way of including the CSS, like this:
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
```

**Comment by dyve** [comment]
The idea of these shortcuts is that the Bootstrap version included matches the Bootstrap version supported by the package.

**Comment by dyve** [comment]
I think @FlipperPA is right. This is a good shortcut for newcomers. Let's fix it.
