### ISSUE TITLE
complex demo for begginers

### ISSUE THREAD

**Issue by luizsfer** [zostera/django-bootstrap4#90]
Hello,

I create a better example for a begginers compreension, maybe, its interesting for the your project.
It's a simple and initial project, but helps my students here.

Link: https://github.com/luizsfer/django-bootstrap4-init

Tks for attention

**Comment by Sidon** [comment]
The example use django+bootstrap but don't use this project. :-1:

**Comment by dyve** [comment]
I will investigate, thanks

**Comment by vadimkim** [comment]
this issue overlaps with this one #84 , but I was able to fix it by installing Geolibs as described[ here](https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/geolibs) and adding ALLOWED_HOSTS to tests/app/settings.py
`
ALLOWED_HOSTS = ['localhost', '127.0.0.1',]
`
But with this 500 error I am stuck

**Comment by dyve** [comment]
We will solve the problem in issue #84. Closing this one.
