### ISSUE TITLE
Different div class for checkboxes

### ISSUE THREAD

**Issue by egorsmkv** [zostera/django-bootstrap4#95]
There is a different div class in the Bootstrap's docs for checkboxes.

https://getbootstrap.com/docs/4.1/components/forms/#overview

Now it's "form-group form-check" but the library generates only the "form-group" div.

**Comment by egorsmkv** [comment]
For Bootstrap 4.0 (https://getbootstrap.com/docs/4.0/components/forms/#overview) it is only the "form-check" div class.

**Comment by sedrubal** [comment]
Alternatively you can use the [custom checkbox](https://getbootstrap.com/docs/4.1/components/forms/#checkboxes) like this:

```html
<div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input" id="id_test_checkbox">
  <label class="custom-control-label" for="id_test_checkbox">Check this custom checkbox</label>
</div>
```
