### ISSUE TITLE
Labels → Badges

### ISSUE THREAD

**Issue by nim65s** [zostera/django-bootstrap4#99]
Hi,

According to [Bootstrap's migration guide](https://getbootstrap.com/docs/4.0/migration/#labels-and-badges), shouldn't we update the [bootstrap_label](https://github.com/zostera/django-bootstrap4/blob/master/bootstrap4/templatetags/bootstrap4.py#L591) function, and eventually rename it to `bootstrap_badge` ?

**Comment by dyve** [comment]
Our `bootstrap_label` generates labels for the form, so it does exactly what it needs to do in Bootstrap4.
